services:
  web:
    depends_on: 
      - api
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/next.config.mjs
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    environment:
        - WATCHPACK_POLLING=true
        - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
       - 5000:5000 
    develop:
      watch:
        - path: ./api/package.json
          action: rebuild
        - path: ./api/package-lock.json
          action: rebuild
        - path: ./api
          target: /app
          action: sync
    environment:
       - WATCHPACK_POLLING=true
       - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./api:/app
      - /app/node_modules
volumes:
  redis: